stages:
  - test
  - deploy

junit:
  stage: test
  script:
    - ./gradlew test

fx_version_check:
  stage: test
  before_script:
    - cd scripts
  script:
    - ./warn_javafx_version_in_fxml.sh

cucumber:
  stage: test
  script:
    - ./gradlew cucumber

generate_artifacts:
  stage: deploy
  script:
    - ./gradlew clean jar
  artifacts:
    paths:
      - build/libs/wino-*.jar