stages:
  - test
  - deploy
  - check_java_src
  - check_fxml

junit:
  stage: test
  script:
    - ./gradlew test

cucumber:
  stage: test
  script:
    - ./gradlew cucumber

ban_print_statements:
  stage: check_java_src
  before_script:
    - cd scripts
  script:
    - ./ban_print_statements.sh

check_javafx_resource_path:
  stage: check_fxml
  before_script:
    - cd scripts
  script:
    - ./check_javafx_path.sh



generate_artifacts:
  stage: deploy
  script:
    - ./gradlew clean jar
  artifacts:
    paths:
      - build/libs/wino-*.jar